### ISSUE TITLE
#816 being used

### ISSUE THREAD

**Issue by legionnaire1211** [legionnaire1211/Quickstart-Training#5]
Extended macro variables shouldn't be used because we cannot know if this option will be available

**Comment by Insolublenitrate** [comment]
CHANGED VARIBLE #816 TO #2 FOR LOCAL AVAILIBILITY

**Comment by Insolublenitrate** [comment]
Move the G68 rotation angle to separate sequence for one-shot call, make variable #2 for saving angle
